### PR TITLE
Reformat models_mixer.py

### PR DESCRIPTION
**Pull request by ClashLuke**

### CODE REVIEW

**Comment by ClashLuke** [comment]
@googlebot I signed it!

**Comment by ClashLuke** [comment]
While it has 17% more lines, people on Yannic Kilcher's Discord server found it much easier to understand than the previous "transpose-MLP-transpose" architecture.\
The performance appears the same when tested with the CIFAR script on a v3-8 via ssh.

**Comment by akolesnikoff** [comment]
Hi @ClashLuke,

Thank you for your effort and for the PR.

Unfortunately, there are a couple of reasons we likely won't merge it. First, we would like to keep the code consistent with the snippet from the paper on arxiv (https://arxiv.org/abs/2105.01601). Second, current implementation is better aligned with  MLP-Mixer's model diagram from the paper.

**Comment by ClashLuke** [comment]
Fair. Thank you for the review.

**Pull request closed without merging**
