### PR TITLE
Adds `PROMPTS80` and code for imagenet2012 evaluation.

### PR DESCRIPTION
**Pull request by andsteing**
See also cmment in #198

### CODE REVIEW

**Comment by sayakpaul** [comment]
Thanks for adding this!

Just wanted to know if it makes sense to also use `pmap()` for mapping the forward pass onto all available devices. Currently, I don't think the Colab is using any accelerator. Sorry if it's already.

**Comment by andsteing** [comment]
I would rather copy the copy from the image embedding, something like

```python
# JIT-compile image embedding function because there are lots of images.
if 'embed_tokens' not in globals():
  @jax.jit
  def embed_tokens(variables, tokens):
    _, ztxt, _ = lit_model.apply(variables, tokens=tokens)
    return ztxt

bs = 1000
zts = []
for step in tqdm.tnrange(int(np.ceil(len(tokens) / bs))):
  zts.append(embed_tokens(lit_variables, tokens=tokens[step*bs:(step+1)*bs]))
ztxt = np.concatenate(zts)
del zts
```

Note that the Colab is running on a GPU runtime by default, so when you say `jax.devices()` you should see the GPU accelerator.

You can simply switch the runtime to TPU and everything will work as expected, using all 8 devices in parallel. It's usually a better idea to use `pmap()` rather than `jit()` so you can later map it on multiple devices seamlessly. Unfortunately Colab is using the legacy "TPU Node" setup, so you don't get so much benefit for image processing when switching to TPU (but this will hopefully change soon).

**Comment by sayakpaul** [comment]
Thanks so much!

**Review by lucasb-eyer — APPROVED** [review]
LGTM

**Comment by sayakpaul** [comment]
@andsteing a noob question again.

I am using the image embedding computing utility on a GCP VM that has two T4s. 

I guess I will need to use `pmap()` for distributing the computation to these two devices?

**Comment by andsteing** [comment]
using 2 T4s: yes that's correct; this codebase should use all GPUs automatically - it's using `pmap()` here:
https://github.com/google-research/vision_transformer/blob/16fc24d2734f34b0a7b16212a4386c41fe662cb4/vit_jax/train.py#L69

**Comment by sayakpaul** [comment]
> using 2 T4s: yes that's correct; this codebase should use all GPUs automatically - it's using `pmap()` here:
> 
> https://github.com/google-research/vision_transformer/blob/16fc24d2734f34b0a7b16212a4386c41fe662cb4/vit_jax/train.py#L69

But I am not using that code, though. I am using the `lit.ipynb` notebook. Thanks for your answer.

**Comment by andsteing** [comment]
I think the Colab is calling above function:
https://colab.sandbox.google.com/github/google-research/vision_transformer/blob/main/vit_jax.ipynb#scrollTo=vzlfREb1ZHBY
```python
# Check out train.make_update_fn in the editor on the right side for details.
lr_fn = utils.create_learning_rate_schedule(total_steps, base_lr, decay_type, warmup_steps)
update_fn_repl = train.make_update_fn(
    apply_fn=model.apply, accum_steps=accum_steps, lr_fn=lr_fn)
# We use a momentum optimizer that uses half precision for state to save
# memory. It als implements the gradient clipping.
opt = momentum_clip.Optimizer(grad_norm_clip=grad_norm_clip).create(params)
opt_repl = flax.jax_utils.replicate(opt)
```

**Comment by sayakpaul** [comment]
Yeah that one is. But I am referring to the lit.ipynb Colab.

**Comment by andsteing** [comment]
aaah right

indeed here we jit the function:
https://colab.research.google.com/github/google-research/vision_transformer/blob/main/lit.ipynb#scrollTo=iO85T44aEmMs
```python
# JIT-compile image embedding function because there are lots of images.
@jax.jit
def embed_images(variables, images):
  zimg, _, _ = lit_model.apply(variables, images=images)
  return zimg
```

you could use e.g. `big_vision.utils.pad_shard_unpad` instead
https://github.com/google-research/big_vision/blob/65599a6e347c4e5325ddb5a88ba02277a607e62a/big_vision/utils.py#L67-L69

note that using `pmap()` and evaluating the entire dataset makes things  bit more complicated, as described here:
https://flax.readthedocs.io/en/latest/howtos/full_eval.html

**Comment by sayakpaul** [comment]
Will give it a go. Thanks 👍

**Pull request merged**
