### PR TITLE
Add config for ViT-XX-gap-norep

### PR DESCRIPTION
**Pull request by juntang-zhuang**
Add configs for 'ViT-S_32-gap-norep', 'ViT-S_16-gap-norep',  'ViT-B_32-gap-norep',  'ViT-B_16-gap-norep', which are compatible with GSAM checkpoints. 

ViT-S_32-gap-norep: https://colab.research.google.com/drive/1menAIRCDxwx6PfUKupFerKOP5Fzm1APp?usp=sharing
ViT-S_16-gap-norep: https://colab.research.google.com/drive/1sAMdbu4GIsMuNCRDyNGgMHxxyBEvXI1h?usp=sharing
ViT-B_32-gap-norep: https://colab.research.google.com/drive/12SGIVL2iigLbdGBQDTZS8aOAfLzwW0KV?usp=sharing
ViT-B_16-gap-norep: https://colab.research.google.com/drive/1sJ4_Rgs_7LK3hfyMnhlQMnnC_nOOwvBH?usp=sharing

### CODE REVIEW

**Comment by andsteing** [comment]
Thanks for updating the configs!

I pulled the following CIFAR10 accuracies (after 100 steps) from your Colabs for reference:

| model | acc |
| --- | --- |
| gsam-S/32 | 95.10 |
| gsam-S/16 | 96.05 |
| gsam-B/32 | 96.21 |
| gsam-B/16 | 96.46 |
| B/16 | 97.62 |

Please also fix the tests to make the Github build action pass - you'll need to update the expected params for the configs you have added here:

https://github.com/google-research/vision_transformer/blob/40c0b7867f1affd8f51c1482736436ddcf42bb69/vit_jax/models_test.py#L25-L48

**Comment by juntang-zhuang** [comment]
@andsteing Thanks a lot for feedback! I added the expected param count in the test file, and the local test is all passed. 

For the finetune results, GSAM results are pre-trained on ImageNet1k, but for ViT models I only found checkpoints pretrained on ImageNet21k, I wonder if there are finetuning results for ViT trained I1k with pure AdamW?

**Comment by andsteing** [comment]
@juntang-zhuang 

No, we only published the `imagenet-21k` checkpoints because they produce strictly better results.

Did you try GSAM pre-training on `imagenet-21k` as well? It would be interesting to see how much the performance can be improved in that setting, maybe even combining with the data augmentation from the [AugReg paper](https://arxiv.org/abs/2106.10270), to see if the improvements are additive.

**Comment by juntang-zhuang** [comment]
@andsteing We did not experiment on ImageNet-21k due to time limits. I'm currently not affiliated with Google, would you or @tingliu be available to try GSAM with more data or augmentation? If time does not permit, we might provide ImageNet checkpoints only.

**Pull request merged**
